var = input('Digite algum valor para a variável: ')

print('O tipo primitivo desse valor é :', type(var))
print('Só tem espaço?', var.isspace)
print('é um numero?', var.isnumeric)
print('é alfabetico?', var.isalpha)
print('é alfanumerico?', var.isalnum)
print('está em maiusculas?', var.isupper)
print('está em minusculas?', var.islower)
print('está capitalizada?', var.istitle)
